#!/bin/bash
julia --project=binder -e '
    import Pluto
    Pluto.run(
        host="0.0.0.0",
        port=parse(Int, ENV["PORT"]),
        launch_browser=false,
        require_secret_for_open_links=false,
        require_secret_for_access=false
    )
'
